[Unit]
Requires=buzz-ci-controld-acceptance.socket buzz-ci-keyholder.socket buzz-ci-runner.socket
After=network-online.target buzz-ci-controld-acceptance.socket buzz-ci-keyholder.socket buzz-ci-runner.socket
Wants=network-online.target

[Service]
PrivateNetwork=no
ReadOnlyPaths=/run/buzzci/keyholder.sock /run/buzzci/runner-control.sock /var/lib/buzzci/activation-controller/controld-acceptance-v1.json
RestrictAddressFamilies=
RestrictAddressFamilies=AF_UNIX AF_INET AF_INET6
