[Unit]
Requires=buzz-ci-controld-acceptance.socket
After=network-online.target buzz-ci-controld-acceptance.socket buzz-ci-keyholder.socket buzz-ci-runner.socket
Wants=network-online.target

[Service]
PrivateNetwork=no
ReadOnlyPaths=/run/buzzci /var/lib/buzzci/activation-controller/controld-acceptance-v2.json
RestrictAddressFamilies=
RestrictAddressFamilies=AF_UNIX AF_INET AF_INET6
