[Unit]
Requires=buzz-ci-keyholder.socket buzz-ci-runner.socket
After=network-online.target buzz-ci-keyholder.socket buzz-ci-runner.socket
Wants=network-online.target

[Service]
PrivateNetwork=no
ReadOnlyPaths=/run/buzzci/keyholder.sock /run/buzzci/runner-control.sock
RestrictAddressFamilies=
RestrictAddressFamilies=AF_UNIX AF_INET AF_INET6
