import path from "node:path";
import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";
import { tanstackRouter } from "@tanstack/router-plugin/vite";

const host = process.env.TAURI_DEV_HOST;

// https://vite.dev/config/
export default defineConfig(async ({ mode }) => ({
  plugins: [
    tanstackRouter({
      target: "react",
      routesDirectory: "./src/app/routes",
      generatedRouteTree: "./src/app/routeTree.gen.ts",
      virtualRouteConfig: "./src/app/routes.ts",
      quoteStyle: "double",
      semicolons: true,
      routeTreeFileHeader: [
        "// biome-ignore-all lint: generated by TanStack Router",
      ],
    }),
    react(),
  ],
  resolve: {
    alias: {
      "@": "/src",
      "@features-manifest": path.resolve(__dirname, "../preview-features.json"),
      ...(mode === "web"
        ? {
            "@tauri-apps/api/app": path.resolve(
              __dirname,
              "src/platform/web/shims/app.ts",
            ),
            "@tauri-apps/api/core": path.resolve(
              __dirname,
              "src/platform/web/shims/core.ts",
            ),
            "@tauri-apps/api/event": path.resolve(
              __dirname,
              "src/platform/web/shims/event.ts",
            ),
            "@tauri-apps/api/mocks": path.resolve(
              __dirname,
              "src/platform/web/shims/mocks.ts",
            ),
            "@tauri-apps/api/path": path.resolve(
              __dirname,
              "src/platform/web/shims/path.ts",
            ),
            "@tauri-apps/api/webview": path.resolve(
              __dirname,
              "src/platform/web/shims/webview.ts",
            ),
            "@tauri-apps/api/window": path.resolve(
              __dirname,
              "src/platform/web/shims/window.ts",
            ),
            "@tauri-apps/plugin-clipboard-manager": path.resolve(
              __dirname,
              "src/platform/web/shims/clipboard.ts",
            ),
            "@tauri-apps/plugin-notification": path.resolve(
              __dirname,
              "src/platform/web/shims/notification.ts",
            ),
            "@tauri-apps/plugin-opener": path.resolve(
              __dirname,
              "src/platform/web/shims/opener.ts",
            ),
            "@tauri-apps/plugin-process": path.resolve(
              __dirname,
              "src/platform/web/shims/process.ts",
            ),
            "@tauri-apps/plugin-updater": path.resolve(
              __dirname,
              "src/platform/web/shims/updater.ts",
            ),
          }
        : {}),
    },
  },

  base: mode === "web" ? "/app/" : undefined,

  // Vite options tailored for Tauri development and only applied in `tauri dev` or `tauri build`
  //
  // 1. prevent Vite from obscuring rust errors
  clearScreen: false,
  // 2. tauri expects a fixed port, fail if that port is not available
  server: {
    port: parseInt(process.env.VITE_PORT || "1420", 10),
    strictPort: true,
    host: host || false,
    hmr: host
      ? {
          protocol: "ws",
          host,
          port: parseInt(process.env.VITE_HMR_PORT || "1421", 10),
        }
      : undefined,
    watch: {
      // 3. tell Vite to ignore watching `src-tauri`
      ignored: ["**/src-tauri/**"],
    },
  },
}));
